version: '3.7'

services:
  django_gunicorn:
    volumes:
      - static:/app/static
    env_file:
      - backend/.env
    build: backend
    ports:
      - "8000:8000"

  nginx:
    build: nginx
    volumes:
      - static:/app/static
    ports:
      - "8080:80"
    depends_on:
      - django_gunicorn
    networks:
      - backend

  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - django_gunicorn

volumes:
  static:

networks:
  backend:
