FROM python:3.10

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY requirements.txt /app/
RUN pip install -r requirements.txt

COPY . /app/

COPY entrypoint.sh /app/

RUN chmod +x entrypoint.sh

CMD ["./entrypoint.sh"]