# Generated by Django 5.0.3 on 2024-04-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Cottages",
        ),
        migrations.AddField(
            model_name="rooms",
            name="is_cottage",
            field=models.BooleanField(default=False),
        ),
    ]
