# Generated by Django 5.0.3 on 2024-04-04 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0003_images"),
    ]

    operations = [
        migrations.RenameField(
            model_name="images",
            old_name="room",
            new_name="room_id",
        ),
    ]
