# Generated by Django 5.0.3 on 2024-04-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0004_rename_room_images_room_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Services",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField()),
            ],
        ),
    ]
