# Generated by Django 5.0.3 on 2024-04-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                ("satisfied", models.CharField(max_length=255)),
                ("message", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("number", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=150)),
            ],
        ),
    ]
